contactus/urls.py
from django.urls import path
from . import views

app_name = 'contactus'

urlpatterns = [
    path('', views.ContactUsCreateView.as_view(), name = 'contactus'),

]

myaccount/urls.py
from django.urls import path
from . import views, api

app_name = 'myaccount'

urlpatterns = [
    path('', views.AccountMessageCreateView.as_view(), name = 'myaccount'),
    path('my-cart', api.CartApi.as_view(), name = 'mycart'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace = 'user')),
    path('portfolio/', include('portfolio.urls', namespace = 'portfolio')),
    path('service/', include('service.urls', namespace = 'service')),
    path('ticket/', include('ticket.urls', namespace = 'ticket')),
    path('contact-us/', include('contactus.urls', namespace = 'contactus')),
    path('my-account/', include('myaccount.urls', namespace = 'myaccount')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from . import views
from .models import Service

app_name = 'service'

urlpatterns = [
    path('', views.Service.as_view(), name = 'all_service'),
    path('<str:slug>', views.ServiceDetailView.as_view(model=Service), name = 'service'),

]

ticket/urls.py
from django.urls import path
from . import views

app_name = 'ticket'

urlpatterns = [
    path('', views.TicketCreateView.as_view(), name = 'ticket'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('login', views.login_view, name = 'login'),
    path('logout', views.logout_view, name = 'logout'),
    path('signup', views.SignUp.as_view(), name = 'signup'),
    path('success', views.success_send, name = 'success'),
    path('success_sign', views.success_sign, name = 'success_sign'),

]

contactus/models.py
from django.db import models
from django.utils import timezone





class ContactUs(models.Model):
    name       = models.CharField(max_length=30, blank=False, null=False)
    email      = models.EmailField(blank=False, null=False, verbose_name='email address')
    message    = models.TextField( blank=False, null=False )

    created_at = models.DateTimeField(default=timezone.now, verbose_name='created at')
    
    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"
    

class ContactInfo(models.Model):
    call_us      = models.CharField(max_length=50, blank=True, null=True)
    email        = models.EmailField()
    offices      = models.CharField(max_length=50, blank=True, null=True)
    facebook_url = models.URLField(blank=True, null=True, verbose_name='facebook url')
    twitter_url  = models.URLField(blank=True, null=True, verbose_name='twitter url')
    whatsapp_url = models.URLField(blank=True, null=True, verbose_name='whatsapp url')
    linkedin_url = models.URLField(blank=True, null=True, verbose_name='linkedin url')

    def __str__(self):
        return str(self.id)
    
    class Meta:
        verbose_name = "Contact Info"
        verbose_name_plural = "Contact Info"

myaccount/models.py
from django.db import models
from user.models import MyUser
from django.utils import timezone
from service.models import Service




class AccountMessage(models.Model):
    created_by = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='created by')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='created at')
    message    = models.TextField( blank=False, null=False ) 
    
    def __str__(self):
        return str(self.id)
    

class MyService(models.Model):
    user       = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    service    = models.ForeignKey(Service, on_delete = models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now, verbose_name='created at')

    def __str__(self):
        return str(self.id)
    
    class Meta:
        verbose_name = "My cart"
        verbose_name_plural = "My cart"
    

portfolio/models.py
from django.db import models
from user.models import MyUser
from django.core.exceptions import ValidationError
import os
from project import settings
from django.core.files.storage import FileSystemStorage
from random import choice
from string import ascii_lowercase, digits
import datetime
from django.utils import timezone
from django.core.files.images import get_image_dimensions




def validate_name(name):
    if not(name) or name.isspace():
        raise ValidationError('empty name is not valid name')   




def generate_name(length=4, chars = ascii_lowercase+digits):
    '''generate name from two sections
        1. random name of 4 letters from chars list
        2. current date and time
    '''
    random_name = ''.join([choice(chars) for i in range(length)])
    dt = datetime.datetime.now()
    dt_str = dt.strftime("%Y%m%d%H%M%S")
    return "%s-%s"%(random_name, dt_str)



def image_upload(instance, filename):
    imgname, *exten = filename.split(".")
    new_name = generate_name() 
    return "portfolio/%s.%s"%(new_name, exten[-1])



class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length = None):
        # If the filename already exists, remove it as if it was a true file system
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


def validate_dimension(image):
    width, height = get_image_dimensions(image)
    if width != 600 or height !=  600:
        raise ValidationError(
            [f'Size should be  600*600.']
            )
    

class PortFolio(models.Model):
    created_by   = models.ForeignKey(MyUser, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='created by')
    created_at   = models.DateTimeField(default=timezone.now, verbose_name='created at')
    project_name = models.CharField(max_length=255, blank=False, null=False, verbose_name='project name')
    image        = models.ImageField(    
                                         upload_to=image_upload,
                                         validators=[validate_dimension],
                                         default = 'portfolio/project.jpg',
                                         storage = OverwriteStorage() 
                                    )
    details      = models.TextField(blank=True, null=True) 


    
    def __str__(self):
        return self.project_name
    

service/models.py
from django.db import models
from user.models import MyUser
from django.core.exceptions import ValidationError
import os
from project import settings
from django.core.files.storage import FileSystemStorage
from random import choice
from string import ascii_lowercase, digits
import datetime
from django.utils import timezone
from django.core.files.images import get_image_dimensions




def validate_name(name):
    if not(name) or name.isspace():
        raise ValidationError('empty name is not valid name')   




def generate_name(length=4, chars = ascii_lowercase+digits):
    '''generate name from two sections
        1. random name of 4 letters from chars list
        2. current date and time
    '''
    random_name = ''.join([choice(chars) for i in range(length)])
    dt = datetime.datetime.now()
    dt_str = dt.strftime("%Y%m%d%H%M%S")
    return "%s-%s"%(random_name, dt_str)



def image_upload(instance, filename):
    imgname, *exten = filename.split(".")
    new_name = generate_name() 
    return "service/%s.%s"%(new_name, exten[-1])



class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length = None):
        # If the filename already exists, remove it as if it was a true file system
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


def validate_dimension(image):
    width, height = get_image_dimensions(image)
    if width != 683 or height !=  1024:
        raise ValidationError(
            [f'Size should be  683*1024.']
            )
    


class ServiceSegment(models.Model):
    title       = models.CharField(max_length=60 ,blank=False, null=False)
    image       = models.ImageField(    
                                         upload_to=image_upload,
                                         validators=[validate_dimension],
                                         default = 'service/service.jpg',
                                         storage = OverwriteStorage() 
                                     )
    figcaption  = models.CharField(max_length=200 ,blank=True, null=True)
    details     = models.TextField(blank=False, null=False) 

    def image_tag(self):
        from django.utils.html import mark_safe
        return mark_safe('<img src="{}" width="150" height="150" />'.format(self.image.url))
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True
    

    
    def __str__(self):
        return str(self.id)


class Service(models.Model):
    created_by   = models.ForeignKey(MyUser, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='created by')
    created_at   = models.DateTimeField(default=timezone.now, verbose_name='created at')
    service_name = models.CharField(max_length=255, blank=False, null=False, verbose_name='service name')
    image        = models.ImageField(    
                                         upload_to=image_upload,
                                         validators=[validate_dimension],
                                         default = 'service/service.jpg',
                                         storage = OverwriteStorage() 
                                     )
    details      = models.CharField(max_length=82, blank=False, null=False) 
    slug         = models.SlugField(max_length = 255, null = False, blank = False, unique=True)

    segments     = models.ManyToManyField(ServiceSegment, blank = True)

    def image_tag(self):
        from django.utils.html import mark_safe
        return mark_safe('<img src="{}" width="150" height="150" />'.format(self.image.url))
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True
    

    
    def __str__(self):
        return self.service_name
    

ticket/models.py
from django.db import models
from user.models import MyUser
from django.utils import timezone





class Ticket(models.Model):
    created_by    = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='created by')
    created_at    = models.DateTimeField(default=timezone.now, verbose_name='created at')

    suitable_time = models.DateTimeField(auto_now=False, auto_now_add=False, verbose_name='suitable time for contact')
    company_name  = models.CharField( max_length=50, blank=False, null=False, verbose_name='company name' )
    work_field    = models.CharField( max_length=50, blank=False, null=False, verbose_name='work field')
    problem_type  = models.CharField( max_length=50, blank=False, null=False, verbose_name='problem type' )
    message       = models.TextField( blank=False, null=False ) 
    
    def __str__(self):
        return self.problem_type
    

contactus/forms.py
from django import forms
from .models import ContactUs



class ContactUsCreateForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('name',
                  'email',
                  'message',
                   )

myaccount/forms.py
from django import forms
from .models import AccountMessage



class AccountMessageCreateForm(forms.ModelForm):
    class Meta:
        model = AccountMessage
        fields = ('message', )

ticket/forms.py
from django import forms
from .models import Ticket



class TicketCreateForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('company_name',
                  'work_field',
                  'problem_type',
                  'suitable_time', 
                  'message',
                   )

contactus/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import ContactUsCreateForm
from .models import ContactInfo








class ContactUsCreateView(CreateView):
    form_class = ContactUsCreateForm
    template_name = 'contact-us.html'
    success_url = reverse_lazy('user:success')

    

myaccount/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import AccountMessageCreateForm
from .models import MyService







class AccountMessageCreateView(LoginRequiredMixin, CreateView):
    form_class = AccountMessageCreateForm
    template_name = 'my-account.html'
    success_url = reverse_lazy('user:success')

    def form_valid(self, form):
        message = form.save(commit=False)
        message.created_by = self.request.user 
        message.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        services = MyService.objects.filter(user = user)
        context['services'] = services
        return context
    

    



    

portfolio/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import PortFolio



class PortFolio(ListView):
    queryset      = PortFolio.objects.all()
    template_name = "portfolio.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        new_object_list = context['object_list']
        nol = self.get_couple(new_object_list)
        coupled_list = list(zip(nol, range(len(nol))))
        context['new_object_list'] = coupled_list
        
        return context
    
    def get_couple(self, x):
        c = [[] for i in range(0,len(x),2)]
        for i,v in enumerate(range(0,len(x), 2)):
            c[i].append(x[v])
            if v+1 < len(x):
                c[i].append(x[v+1])
        return c

service/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Service
from myaccount.models import MyService



class Service(ListView):
    queryset      = Service.objects.all()
    template_name = "service.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        new_object_list = context['object_list']
        nol = self.get_triple(new_object_list)
        triple_list = list(zip(nol, range(len(nol))))
        context['new_object_list'] = triple_list

        if self.request.user.is_authenticated:
            my_cart     = MyService.objects.filter(user = self.request.user)
            my_services = [i.service for i in my_cart]
            context['my_services'] = my_services
        return context
    
    def get_triple(self, x):
        c = [[] for i in range(0,len(x),3)]
        for i,v in enumerate(range(0,len(x), 3)):
            c[i].append(x[v])
            if v+1 < len(x):
                c[i].append(x[v+1])
            if v+2 < len(x):
                c[i].append(x[v+2])
        return c




class ServiceDetailView(DetailView):
    template_name = 'service_detail.html'

ticket/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import TicketCreateForm








class TicketCreateView(LoginRequiredMixin, CreateView):
    form_class = TicketCreateForm
    template_name = 'ticket.html'
    success_url = reverse_lazy(('user:success'))

    def form_valid(self, form):
        ticket = form.save(commit=False)
        ticket.created_by = self.request.user 
        ticket.save()
        return super().form_valid(form)
    

templates/comments-feed.html
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>
	Comments for IPAM Develop	</title>
	<atom:link href="https://ipamdevelop.com/comments/feed/" rel="self" type="application/rss+xml" />
	<link>https://ipamdevelop.com</link>
	<description></description>
	<lastBuildDate>Wed, 01 Feb 2023 11:06:36 +0000</lastBuildDate>
	<sy:updatePeriod>
	hourly	</sy:updatePeriod>
	<sy:updateFrequency>
	1	</sy:updateFrequency>
	<generator>https://wordpress.org/?v=6.3</generator>
</channel>
</rss>

templates/login.html
{% extends "base.html" %}
{% load static %}



{% block content %}
	

	<main id="content" class="neve-main">

<div class="container single-page-container">
	<div class="row">
				<div class="nv-single-page-wrap col">
			<div class="nv-content-wrap entry-content">


<div class="wp-block-cover alignfull" style="min-height:600px"><span aria-hidden="true" class="wp-block-cover__background has-nv-dark-bg-background-color has-background-dim-100 has-background-dim"></span><div class="wp-block-cover__inner-container is-layout-flow wp-block-cover-is-layout-flow">
<div class="wp-block-group is-layout-flow wp-block-group-is-layout-flow"><div class="wp-block-group__inner-container">
<div style="height:80px" aria-hidden="true" class="wp-block-spacer"></div>



<div class="wp-block-columns is-layout-flex wp-container-14 wp-block-columns-is-layout-flex">
<div class="wp-block-column is-layout-flow wp-block-column-is-layout-flow" style="flex-basis:50%">
<h2 class="has-nv-text-dark-bg-color has-text-color wp-block-heading">Send us a message or Come visit us</h2>





<ul class="wp-block-social-links has-normal-icon-size is-style-pill-shape is-layout-flex wp-block-social-links-is-layout-flex">
	
	<li class="wp-social-link wp-social-link-facebook  wp-block-social-link">
		{% if contact_info.facebook_url %}
			<a href="{{contact_info.facebook_url}}" class="wp-block-social-link-anchor">
		{% else %}
			<a href="" class="wp-block-social-link-anchor">
		{% endif %}
			<svg width="24" height="24" viewbox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
				<path d="M12 2C6.5 2 2 6.5 2 12c0 5 3.7 9.1 8.4 9.9v-7H7.9V12h2.5V9.8c0-2.5 1.5-3.9 3.8-3.9 1.1 0 2.2.2 2.2.2v2.5h-1.3c-1.2 0-1.6.8-1.6 1.6V12h2.8l-.4 2.9h-2.3v7C18.3 21.1 22 17 22 12c0-5.5-4.5-10-10-10z"></path>
			</svg>
			<span class="wp-block-social-link-label screen-reader-text">Facebook</span>
		</a>
	</li>

	<li class="wp-social-link wp-social-link-twitter  wp-block-social-link">
		{% if contact_info.twitter_url %}
			<a href="{{contact_info.twitter_url}}" class="wp-block-social-link-anchor">
		{% else %}
			<a href="" class="wp-block-social-link-anchor">
		{% endif %}
			<svg width="24" height="24" viewbox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
				<path d="M22.23,5.924c-0.736,0.326-1.527,0.547-2.357,0.646c0.847-0.508,1.498-1.312,1.804-2.27 c-0.793,0.47-1.671,0.812-2.606,0.996C18.324,4.498,17.257,4,16.077,4c-2.266,0-4.103,1.837-4.103,4.103 c0,0.322,0.036,0.635,0.106,0.935C8.67,8.867,5.647,7.234,3.623,4.751C3.27,5.357,3.067,6.062,3.067,6.814 c0,1.424,0.724,2.679,1.825,3.415c-0.673-0.021-1.305-0.206-1.859-0.513c0,0.017,0,0.034,0,0.052c0,1.988,1.414,3.647,3.292,4.023 c-0.344,0.094-0.707,0.144-1.081,0.144c-0.264,0-0.521-0.026-0.772-0.074c0.522,1.63,2.038,2.816,3.833,2.85 c-1.404,1.1-3.174,1.756-5.096,1.756c-0.331,0-0.658-0.019-0.979-0.057c1.816,1.164,3.973,1.843,6.29,1.843 c7.547,0,11.675-6.252,11.675-11.675c0-0.178-0.004-0.355-0.012-0.531C20.985,7.47,21.68,6.747,22.23,5.924z"></path>
			</svg>
			<span class="wp-block-social-link-label screen-reader-text">Twitter</span>
		</a>
	</li>

	
	<li class="wp-social-link wp-social-link-whatsapp  wp-block-social-link">
		{% if contact_info.whatsapp_url %}
			<a href="{{contact_info.whatsapp_url}}" class="wp-block-social-link-anchor">
		{% else %}
			<a href="" class="wp-block-social-link-anchor">
		{% endif %}
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
				<path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
			</svg>
			<span class="wp-block-social-link-label screen-reader-text">wahtsapp</span>
		</a>
	</li>

	<li class="wp-social-link wp-social-link-linkedin  wp-block-social-link">
		{% if contact_info.linkedin_url %}
			<a href="{{contact_info.linkedin_url}}" class="wp-block-social-link-anchor">
		{% else %}
			<a href="" class="wp-block-social-link-anchor">
		{% endif %}
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
				<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
			</svg>
			<span class="wp-block-social-link-label screen-reader-text">linkedin</span>
		</a>

</ul>


</div>



<div class="wp-block-column is-vertically-aligned-center is-layout-flow wp-block-column-is-layout-flow" style="flex-basis:50%">


<div id="wp-block-themeisle-blocks-form-5a53b94c" class="wp-block-themeisle-blocks-form" data-option-name="bf9b28ff82ce323187abc5d0feb0d8f07ecd8436_5a53b94c">

	
	<form method="POST" class="form form-short" style="width:100%;">

		{% csrf_token %}

		<div class="title">Login</div>
		<div class="subtitle">Let's login!</div>
		{% if error %}
			<p style="color:red;">{{error}}</p>
		{% endif %}

		<div class="input-container ic1">
		<input id="username" name="username" class="input" type="text" placeholder="" />
		<div class="cut"></div>
		<label for="username" class="placeholder">username</label>
		</div>

		<div class="input-container ic2">
		<input id="password" name="password" class="input" type="password" placeholder="" />
		<div class="cut cut"></div>
		<label for="password" class="placeholder">password</label>
		</div>
		<button type="submit" class="submit">Login</button>

		<div class="subtitle">if not registered <a href="{% url 'user:signup' %}">signup</a> now</div>
	</form>
	
</div>
</div>
</div>



<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
</div></div>
</div></div>
</div>		</div>
			</div>
</div>

</main><!--/.neve-main-->


{% endblock content %}

templates/service.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}


{% block content %}
	<main id="content" class="neve-main">

<div class="container single-page-container">
	<div class="row">
				<div class="nv-single-page-wrap col">
			<div class="nv-content-wrap entry-content">
<div class="wp-block-cover alignfull" style="min-height:300px"><span aria-hidden="true" class="wp-block-cover__background has-nv-site-bg-background-color has-background-dim-100 has-background-dim"></span><div class="wp-block-cover__inner-container is-layout-flow wp-block-cover-is-layout-flow">
<div class="wp-block-group is-layout-flow wp-block-group-is-layout-flow"><div class="wp-block-group__inner-container">
<h1 class="has-text-align-left has-neve-text-color-color has-text-color wp-block-heading">Service</h1>
</div></div>
</div></div>






<!--start -->
  
{% for list, num in new_object_list %}
		{% if num|divisibleby:"2" %}
			<div class="wp-block-cover alignfull" style="min-height:600px"><span aria-hidden="true" class="wp-block-cover__background has-nv-light-bg-background-color has-background-dim-100 has-background-dim"></span><div class="wp-block-cover__inner-container is-layout-flow wp-block-cover-is-layout-flow">
		{% else %}
			<div class="wp-block-cover alignfull" style="min-height:600px"><span aria-hidden="true" class="wp-block-cover__background has-nv-site-bg-background-color has-background-dim-100 has-background-dim"></span><div class="wp-block-cover__inner-container is-layout-flow wp-block-cover-is-layout-flow">
		{% endif %}

		<div class="wp-block-group is-layout-flow wp-block-group-is-layout-flow"><div class="wp-block-group__inner-container">
		<div style="height:80px" aria-hidden="true" class="wp-block-spacer"></div>
		<div class="wp-block-columns are-vertically-aligned-center is-layout-flex wp-container-7 wp-block-columns-is-layout-flex">		

		{% for service in list %}
			
			<div style="display:inline-block; text-align:center;" class="wp-block-column is-vertically-aligned-center is-layout-flow wp-block-column-is-layout-flow" style="flex-basis:50%">
				<a href="{% url 'service:service' service.slug %}">
					<figure class="wp-block-image size-large"><img decoding="async" src="{{service.image.url}}" alt="" class="wp-image-37"></figure>
				</a>
				<h3 class="has-text-align-center has-neve-text-color-color has-text-color wp-block-heading">{{service.service_name}}</h3>
				<p class="has-text-align-center has-neve-text-color-color has-text-color">
					{{ service.details}}
				</p>

				<div class="wp-block-buttons is-content-justification-center is-layout-flex wp-container-3 wp-block-buttons-is-layout-flex">
				
				{% if request.user.is_authenticated %}
					{% if  service in my_services %}
						<div class="wp-block-button is-style-primary">
							<a class="wp-block-button__link"
								href="{% url 'myaccount:myaccount' %}#my_services"
							>
								Added
							</a>
						</div>
					{% else %}
						<div class="wp-block-button is-style-primary">
							<a class="wp-block-button__link"
								onclick="add_to_cart(this)" 
								id="{{service.id}}"
								name="add"
							>
								Add
							</a>
						</div>
					{% endif %}
				{% else %}
					<div class="wp-block-button is-style-primary">
						<a class="wp-block-button__link"
							href="{% url 'user:login' %}"
							id="{{service.id}}"
							name="add"
						>
							Add
						</a>
					</div>
				{% endif %}
			</div>


				
				<div style="height:40px" aria-hidden="true" class="wp-block-spacer">
				</div>
			</div>
			

		{% endfor %}

		</div>
		<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
		</div></div>
		</div></div>


	{% endfor %}


<!--############################## -->





</div>		</div>
			</div>
</div>

</main><!--/.neve-main-->

{% endblock content %}